### PR TITLE
Updated location

### LINKED ISSUE #3: Fix reference to location on homepage
Currently references MADE - should be CritiqueIt.

### PR DESCRIPTION
**Pull request by rogerhoward**
Updates location of Code && Coffee meetup.

Closes #3

### CODE REVIEW

**Comment by mediadoneright** [comment]
looks good.  btw, you should be able to do this... It's GIT,,, we can always roll-back.  I prefer to trust and empower people to help

**Comment by mediadoneright** [comment]
hmm.... I'm having trouble myself.  maybe teams were never setup correctly again

**Comment by rogerhoward** [comment]
No worries - happy to merge my own, but as a general rule (on teams) I never let the person opening the PR also do the merge… good to have a check. If you’d rather me just merge, happy to do so.

**Comment by mdrmike** [comment]
ah!  I guess it helps to utilize a user with permissions.  (I should probably add myself as a user with write access :-P  )

**Comment by mdrmike** [comment]
@rogerhoward missed your comment earlier... understand your rule, and in a work setting agree.  I'm ok either way.  :100: 

That said, since there is a clear, secure, & public audit log, I favor empowering and allowing contribution -- and managing problems if/when they arise.  In future, go for it!!!  ... or leave it.  up to you  :smile:

**Comment by rogerhoward** [comment]
@mediadoneright - still no idea why this broke, the change is really minor and rendering fine on my end. Did you get notices from Github about a build failure? You may have to tweak one or two settings in config to support the new Jekyll 3 backend, but for my other sites that was a quick fix. 

IIRC, I had to use:

```
markdown: redcarpet
highlighter: pygments
```

But since those are already set correctly, not sure what else is wrong. Did Github send you a build failure report?

**Comment by mdrmike** [comment]
ya, its a problem with Jekyll 3.0.2  ... no longer renders files with future dates (`_posts/2025-01-01--Intro.md` I think is the problem child)  ... a stupid trick I used to sort the file processing ... but turns out my local environment was no longer setup -- so in the process of debugging I've decided to update my environment.  plus have dinner.  yay!  

Regarding your fixes, be aware `redcarpet` is being depreciated May 1, 2016 (in favor of kramdown).  I already had `pygments`. Thanks though!

**Comment by mdrmike** [comment]
@rogerhoward side note of the last daye, `pygments` has been depreciated in favor of `rouge` for Jekyll 3.

**Pull request merged**
